<?php

namespace AppBundle\Repository;

/**
 * BeneficiariasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiariasRepository extends \Doctrine\ORM\EntityRepository
{
}
