<?php

namespace AppBundle\Repository;

/**
 * ImpactoSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpactoSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
