<?php

namespace AppBundle\Repository;

/**
 * PlanEstrategicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEstrategicoRepository extends \Doctrine\ORM\EntityRepository
{
}
