<?php

namespace AppBundle\Repository;

/**
 * PoblacionVulnerableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoblacionVulnerableRepository extends \Doctrine\ORM\EntityRepository
{
}
