<?php

namespace AppBundle\Repository;

/**
 * Prog_PagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Prog_PagoRepository extends \Doctrine\ORM\EntityRepository
{
}
