<?php

namespace AppBundle\Repository;

/**
 * ProjectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectoRepository extends \Doctrine\ORM\EntityRepository
{
}
