<?php

namespace AppBundle\Repository;

/**
 * TipoFinanciacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFinanciacionRepository extends \Doctrine\ORM\EntityRepository
{
}
