<?php

namespace AppBundle\Repository;

/**
 * TipoAdministracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAdministracionRepository extends \Doctrine\ORM\EntityRepository
{
}
